### ISSUE TITLE
UTF chars problem as comments 

### ISSUE THREAD

**Issue by platipusica** [thombashi/sqliteschema#3]
Hi there, 

for example:
CREATE TABLE `Сценарии2` (`ИмяС` INTEGER, -- ИмяС:
`idС` INTEGER, -- idС:
`Активатор` VARCHAR(255) DEFAULT '', -- Активатор:
`Функция` VARCHAR(255) DEFAULT '', -- Функция:
`idП` INTEGER  -- idП:
); 

Please try.

Thanks

**Comment by platipusica** [comment]
Bump!

**Comment by thombashi** [comment]
@platipusica 
I'm not sure what is the problem.
Please provide more information:
- Environment information: OS, Python version, etc.
- sqliteschema version
- Error logs
- Reproduction steps

**Comment by platipusica** [comment]
Hi

thank you for the reply!

Please create the table as provided with UTF8 comments. I used the same
method as issue #1, memory table.

All python affected, newest sqliteschema version.
The comments will produce gibberish for result.

Thanks

**Comment by thombashi** [comment]
Thank you for your information.
This will not the issue of `sqliteschema`.
You can get the original comments if you remove the `json.dumps` method call.
